### ISSUE TITLE
Distances don't seem correct

### ISSUE THREAD

**Issue by seancarmody** [pvandegeer/GeometryShapes#2]
Aiming to create a 10km circle, I created an oval with x and y radii both set to 10000m but the radius of the resulting circle was only just over 8km in radius. Not sure whether it's a bug or I've misunderstood something. Using CRS EPSG:3577

**Comment by seancarmody** [comment]
I think I've solved it by switching to a UTM projection - is that correct?

**Comment by pvandegeer** [comment]
Hard to say, for me, why some projections work and others don't. Glad you figured it out. 
I think it works best with the most local/small projections available.
